# Server
server:
  port: 8090

# Mongo
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: dbCustomer

# Log Level
logging:
  level:
    com:
      example:
        customer: DEBUG